# Generated by Django 6.0.3 on 2026-04-16 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='Артикул')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('unit', models.CharField(default='шт.', max_length=20, verbose_name='Единица Измерения')),
                ('supplier', models.CharField(max_length=100, verbose_name='Поставщик')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Скидка')),
                ('stock', models.PositiveBigIntegerField(default=0, verbose_name='Количество на складе')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='images/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Номер Заказа')),
                ('order_date', models.DateField(verbose_name='Дата заказа')),
                ('delivery_date', models.DateField(verbose_name='Дата доставки')),
                ('status', models.CharField(choices=[('Завершен', 'Завершен'), ('Новый', 'Новый')], max_length=30, verbose_name='Статус заказа')),
                ('receiver_name', models.CharField(max_length=50, verbose_name='Имя получателя')),
                ('delivery_code', models.CharField(max_length=30, verbose_name='Код для получения')),
                ('delivery_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.deliverypoint', verbose_name='Адрес пункта выдачи')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantity', models.PositiveIntegerField(default=1, verbose_name='Кол-во')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='project_app.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project_app.product', verbose_name='Товар')),
            ],
        ),
    ]
