# Generated by Django 6.0.3 on 2026-04-16 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='receiver_name',
        ),
    ]
