# Generated by Django 6.0.3 on 2026-04-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('completed', 'Завершен'), ('new', 'Новый')], max_length=30, verbose_name='Статус заказа'),
        ),
    ]
