# Generated by Django 6.0.3 on 2026-04-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Завершен', 'Завершен'), ('Новый', 'Новый')], max_length=30, verbose_name='Статус заказа'),
        ),
    ]
