# Generated by Django 6.0.3 on 2026-04-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_code',
            field=models.CharField(max_length=30, verbose_name='Код для получения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='receiver_name',
            field=models.CharField(max_length=50, verbose_name='Имя получателя'),
        ),
    ]
